### ISSUE TITLE
XML parse error

### ISSUE THREAD

**Issue by Gandorhar** [asrbic/Procedural_Ore_Generator#8]
when I run the run.bat it gives me an XML error 
"Unable to parse "D:\Games\Steam\steamapps\common\SpaceEngineers\Content\Data 
java.io.FileNotFoundException: D:\Games\Steam\steamapps\common\SpaceEngineers\Content\Data (Access Denied)"

I tried to run the .bat as admin and also tried to put the files into another directory, I always get the same error.

This is what I see in the cmd after i close the error message:
 C:\Users\User\Desktop\SE ProOreGen>java -jar -Xms512m -Xmx4g Procedural_Ore_Generator.jar
19:49:11.456 [main] INFO  Main - Attempting to load config.json
19:49:11.501 [main] INFO  XMLConfigUpdater - Attempting to update PlanetGeneratorDefinitions file(s)..
19:54:48.232 [main] ERROR XMLConfigUpdater - Unable to parse D:\Games\Steam\steamapps\common\SpaceEngineers\Content\Data
java.io.FileNotFoundException: D:\Games\Steam\steamapps\common\SpaceEngineers\Content\Data (Zugriff verweigert)
19:54:48.232 [main] ERROR Main - Failed, exception occurred:
java.io.FileNotFoundException: D:\Games\Steam\steamapps\common\SpaceEngineers\Content\Data (Zugriff verweigert)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_281]
        at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_281]
        at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_281]
        at nu.xom.Builder.build(Unknown Source) ~[xom-1.2.5.jar:1.2.5]
        at xml.XMLConfigUpdater.updatePlanetGeneratorDefinitions(XMLConfigUpdater.java:51) ~[Procedural_Ore_Generator.jar:?]
        at core.Main.run(Main.java:71) ~[Procedural_Ore_Generator.jar:?]
        at core.Main.main(Main.java:37) [Procedural_Ore_Generator.jar:?]
19:54:48.239 [main] INFO  Main - Done. Press the ENTER key to exit

**Comment by asrbic** [comment]
planetGeneratorDefinitionsPathArray and planetGeneratorDefinitionsPath should point to the sbc files, not the Data directory eg. "D:\Games\Steam\steamapps\common\SpaceEngineers\Content\Data\PlanetGeneratorDefinitions.sbc"
